name: Check-style
on:
    push:
    pull_request:

jobs:
    check-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js environment
              uses: actions/setup-node@v6
              with:
                  node-version: 22.x
            - name: Install Prettier
              run: npm i -g prettier
            - name: Prettier check
              run: prettier --check .
