name: Publish

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: 'Dry run'
                type: boolean
                required: false
                default: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: NPM Publish
              uses: JS-DevTools/npm-publish@66e0e1d9494ba904d4d608ae77fc5f4fe9bcc038
              with:
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}
                  dry-run: ${{ github.event.inputs.dry-run == 'true' }}

    draft-release:
        needs: [build]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event.inputs.dry-run != 'true'
        permissions: write-all
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get version
              id: version
              run: echo "version=$(node -p 'require(`./package.json`).version')" >> $GITHUB_ENV
              shell: bash
            - name: Create Release
              uses: ncipollo/release-action@v1
              if: github.event.inputs.dry-run != 'true'
              with:
                generateReleaseNotes: true
                draft: true
                tag: v${{ env.version }}
                token: ${{ secrets.GITHUB_TOKEN }}
